export const ONLYWORLDS_CATEGORIES = [
  'character',
  'object',
  'location',
  'family',
  'creature',
  'institution',
  'trait',
  'species',
  'zone',
  'ability',
  'collective',
  'title',
  'language',
  'phenomenon',
  'law',
  'relation',
  'event',
  'construct',
  'marker',
  'pin',
  'narrative',
  'map',
  'world'
] as const;

export type OnlyWorldsCategory = typeof ONLYWORLDS_CATEGORIES[number];

export const CATEGORY_ICONS: Record<OnlyWorldsCategory, string> = {
  character: 'person_4',
  object: 'webhook',
  location: 'castle',
  family: 'supervisor_account',
  creature: 'bug_report',
  institution: 'business',
  trait: 'flaky',
  species: 'crib',
  zone: 'architecture',
  ability: 'auto_fix_normal',
  collective: 'groups_3',
  title: 'military_tech',
  language: 'edit_road',
  phenomenon: 'thunderstorm',
  law: 'gpp_bad',
  relation: 'link',
  event: 'saved_search',
  construct: 'api',
  marker: 'place',
  pin: 'push_pin',
  narrative: 'menu_book',
  map: 'map',
  world: 'public'
};

export const CATEGORY_DISPLAY_NAMES: Record<OnlyWorldsCategory, string> = {
  character: 'Character',
  object: 'Object',
  location: 'Location',
  family: 'Family',
  creature: 'Creature',
  institution: 'Institution',
  trait: 'Trait',
  species: 'Species',
  zone: 'Zone',
  ability: 'Ability',
  collective: 'Collective',
  title: 'Title',
  language: 'Language',
  phenomenon: 'Phenomenon',
  law: 'Law',
  relation: 'Relation',
  event: 'Event',
  construct: 'Construct',
  marker: 'Marker',
  pin: 'Pin',
  narrative: 'Narrative',
  map: 'Map',
  world: 'World'
};